name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Create test file config
      run: |
        cp test.sample.yml test.yml
        sed -i "s/${GOOGLE_ACCESS_TOKEN}/${{ secrets.GOOGLE_ACCESS_TOKEN }}/g" test.yml
        sed -i "s/${GOOGLE_CLEINT_SECRET}/${{ secrets.GOOGLE_CLEINT_SECRET }}/g" test.yml
        sed -i "s/${GOOGLE_CLIENT_ID}/${{ secrets.GOOGLE_CLIENT_ID }}/g" test.yml
        sed -i "s/${GOOGLE_TEST_LIST_ID}/${{ secrets.GOOGLE_TEST_LIST_ID }}/g" test.yml
        sed -i "s/${GOOGLE_REFRESH_TOKEN}/${{ secrets.GOOGLE_REFRESH_TOKEN }}/g" test.yml
        sed -i "s/${NOTION_STATUS}/${{ env.NOTION_STATUS }}/g" test.yml
        sed -i "s/${NOTION_DEADLINE}/${{ env.NOTION_DEADLINE }}/g" test.yml
        sed -i "s/${NOTION_TEST_DB_ID}/${{ secrets.NOTION_TEST_DB_ID }}/g" test.yml
        sed -i "s/${NOTION_STATUS_DONE_VALUE}/${{ env.NOTION_STATUS_DONE_VALUE }}/g" test.yml
        sed -i "s/${NOTION_NAME}/${{ env.NOTION_NAME }}/g" test.yml
        sed -i "s/${NOTION_TOKEN}/${{ secrets.NOTION_TOKEN }}/g" test.yml
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
